services:
  db:
    image: postgres:latest
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    container_name: prisma_migrate
    command: ["npx", "prisma", "migrate", "deploy"]
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    depends_on:
      - db

volumes:
  postgres_data: