apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggtsaastemplate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggtsaastemplate
  template:
    metadata:
      labels:
        app: ggtsaastemplate
    spec:
      containers:
        - name: ggtsaastemplate
          image: ratewar/ggtsaastemplate:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000