apiVersion: v1
kind: Service
metadata:
  name: ggtsaastemplate
  namespace: default
spec:
  selector:
    app: ggtsaastemplate
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000